language: java
jdk:
  - oraclejdk8
script:
  - ./gradlew test
notifications:
  slack:
    secure: zip37bfwnHu6pV/AG6DkWXdL3+4aQWTUhcwj3mEB6Mb4q47ylPWyMRzSXznu8rransVYQVdm3M5F+eQocMsfWtJYgw5amwlZ0qn6V6LVgDP8x1ui6IkGrgig+zoOnKc81aEs+dEEELCVkur982Gz2tvLV90POAsUkcHRV3QqIiqEZHanqIehVUtXtLDQWMgSevjETyH4yrQMOu1V7G6UvoGJTGrsn9x4fbo7dvpvbY/FXPB2xaJpQ0G5CiNf+KyplnRrEoywkAYUfXLS+y84kDUs470+BC+BcJURMl2PSlC/DbHSGpSVrTyExrgg1H4KkRDbSHw3U5hA6fTuUfAycXDgQAkSODjoce7VHzzLNNS5VRhNPhNEgnWnjqlhbc4xiq7VAZCI400eMn1Q7e6Pl9P5gpB0k8f1y/zxB563B7KZktJxj8HYWsVJNqG/BTSm/1c5OS8D5SgTlh2BvzAXWmuQ/QrHTsrmg5u8/swHOOiCKT87hH6abXo6NtcmsE7KK1ryGmjlAe2UaArmQ7PtAy1fk5JhFUY/pCba5mb1mP0qe57V5FC5kuQznesRCfL4JCbx8a3df+lsu1qJslSFQe5/TGIrNNnbfE2yceYj+Pa73FkbFL0B3uPgqHgkljVWiclG2H9+ZqcM8Gd54QV2Uw84SD/CqLmT6P+aNY+oAsQ=
