spring:
  application:
    name: CocktailGuruServer
  datasource:
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        strategy: org.hibernate.cfg.EJB3NamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


endpoints:
  enabled: false
  health:
    enabled: true

management:
  security:
    enabled: false


security:
  basic:
    enabled: true

#logging:
#  file:  /home/spring/logs/${spring.application.name}.log
#  config: logback-spring.xml
#  path: /home/spring/logs/
#logback:
#  access:
#    config: logback-access.xml
#    enabled: true