spring:
  application:
    name: CocktailGuruServer
  datasource:
    tomcat:
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 60000
      validationQuery: SELECT 1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jackson:
    serialization:
      write_dates_as_timestamps: false
  flyway:
    check-location: true
    encoding: utf8
    enabled: true
    locations: classpath:db/migration
    table: schema_version

management:
  endpoint:
    health:
      enabled: true
      show-details: when_authorized
  endpoints:
    enabled-by-default: false