spring:
  profiles.active : develop


  datasource:
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernatedialect.MySQL5Dialect


logging:
  level:
    ROOT: INFO
  file: server.log
