ALTER TABLE `cocktail_dev`.`coctail`
DROP COLUMN `kcalVolume`,
DROP COLUMN `flavorId`,
DROP COLUMN `flavor`,
DROP COLUMN `dataCol`,
DROP COLUMN `numPrepared`,
DROP COLUMN `groupType`,
DROP COLUMN `groupType2`,
DROP COLUMN `groupType3`;